POST http://localhost:8081/api/v1/brigade/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiVVNFUiIsImlkIjoiMzhlM2ZjNTUtZmYyNC00Zjg3LThlODktYTBmYjM0YjdkNjQ1In0.Tcp0mdmyq-WaFSF68o9IXwmrMYAtFsVR8eUfmiYtxHI
Content-Type: application/json

{
  "carId": "66467833-5583-46fa-a0b8-04e84666eeee",
  "regionId": "0ceffd15-3f45-429b-9543-53a596f7a720",
  "doctorId": "43b880ac-9cb7-4d14-bc30-e85ffa1d0c22"
}