POST http://localhost:8081/api/v1/doctor/create
Content-Type: application/json

{
  "regionId": "e4381036-5cf5-11ee-8c99-0242ac120002",
  "name": "Jasmina",
  "surname": "Odilova",
  "phoneNumber": "+998337806713"
}