POST http://localhost:8081/api/v1/region/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJpZCI6IjJlMTUxNzcyLTM2ZWMtNDlhNC05OGU2LThlZjJhMzcyNTE0MSJ9.tHbM-IWk5JnX0cHseg2DzMnOZ6iGtzZn39t0fjyiM34
Content-Type: application/json

{
  "name": "Olmazor"
}