POST http://localhost:8081/api/v1/region/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJpZCI6IjIzZjJiNDlkLWE3MTQtNGJhZC1iNjE1LTBiMTYwMzBhMmJmYyJ9.wQULmoS5Ln3crZ_H4w2HU2i0u-CB9euIKWFZCJRPHxU
Content-Type: application/json

{
  "name": "Olmazor"
}