POST http://localhost:8081/api/v1/region/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiVVNFUiIsImlkIjoiMzhlM2ZjNTUtZmYyNC00Zjg3LThlODktYTBmYjM0YjdkNjQ1In0.Tcp0mdmyq-WaFSF68o9IXwmrMYAtFsVR8eUfmiYtxHI
Content-Type: application/json

{
  "name": "Olmazor"
}